### ISSUE TITLE
exported a graph and file had no title, axes labels, etc.

### ISSUE THREAD

**Issue by nbunker** [equitablegrowth/Playfair#75] opened 2015-12-21 16:46 UTC
![playfair_graph](https://cloud.githubusercontent.com/assets/9907459/11935899/6e26aac2-a7d8-11e5-94b2-93da5f9c0adf.png)

On the second attempt the graph came out fine, but first time it was all messed up

**Comment by austinclemens** [comment] 2015-12-21 17:25
this kinda thing is hard to trouble shoot - if you see it again, get me when it happens so I can take a look at it in the browser

**Comment by austinclemens** [comment] 2016-04-28 19:31
gonna close this since it hasn't been reproduced since then.

**Closed by austinclemens** 2016-04-28 19:31 UTC
Labels: bug
